# Generated by Django 4.1.4 on 2023-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faicon', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
