# Generated by Django 4.1.4 on 2023-01-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='record',
        ),
    ]
